(menhir (modules nkpl_parser) (flags --explain --dump --exn-carries-state))

(env
  (dev
    (flags (:standard -warn-error -A -w -58))))

(library
  (name netkat_netkat)
  (public_name netkat.netkat)
  (instrumentation (backend landmarks))
  (preprocess (pps landmarks-ppx sedlex.ppx ppx_sexp ppx_deriving.std))
  (libraries landmarks unix yojson menhirLib sedlex str ego z3))

(documentation
  (package netkat)
  (mld_files :standard))
